apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-product2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app2
    server: {{ .Values.spec.destination.server }}
  project: produit2
  source:
    path: produit2
    repoURL: https://github.com/lyc-handson-aws/handson-topic10-product2.git
    targetRevision: HEAD
    kustomize:
      namePrefix: app2-
      patches:
        - target:
            group: app.lyc-handson-aws.com
            version: v1alpha1
            kind: TopicTen
            name: topicten
          patch: |-
            - op: replace
              path: /spec/replicas
              value: 4
            - op: replace
              path: /spec/cloudwatcharn
              value: "arn:aws:logs:eu-west-3:654654303557:log-group:service2-topic10-loggroup:*"
            - op: replace
              path: /spec/kmsarn
              value: "arn:aws:kms:eu-west-3:654654303557:key/ede6fc6a-83d4-4100-b867-62adcf74ffec"
            - op: replace
              path: /spec/targetarn
              value: "arn:aws:s3:::service2-topic10-xr-mmrzg-4tcz6"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

  