apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-service2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app2
    server: {{ .Values.spec.destination.server }}
  project: produit2
  source:
    path: service2/xr
    repoURL: https://github.com/lyc-handson-aws/handson-topic10-services.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true