apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/app1
    repoURL: https://github.com/lyc-handson-aws/handson-topic10.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

