apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/app2
    repoURL: https://github.com/lyc-handson-aws/handson-topic10.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true