apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-secret1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app1
    server: {{ .Values.spec.destination.server }}
  project: produit1
  source:
    path: secrets
    repoURL: https://github.com/lyc-handson-aws/handson-topic10-product1.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true